# Port chạy server mặc định
server.port=8080

# Chuỗi kết nối đến SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AMS_HTV2020;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate (none để không tự động sửa bảng của DB có sẵn)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl